stages:
  - register
  - images
  - unregister

.image:
  image: docker:17.12
  stage: images
  services:
    - docker:17.12-dind
  variables:
    DOCKER_DRIVER: overlay2
  before_script:
    - apk add --no-cache make bash
  script:
    - make all

.runner:
  image:
    name: hashicorp/terraform:0.12.21
    entrypoint: [""]
  before_script:
    - export RUNNER_ARCH=$(echo $CI_JOB_NAME|sed 's,.*:,,g')
    - cd ci/scway/$RUNNER_ARCH
    - terraform init

register:arm:
  extends: .runner
  stage: register
  script:
    - terraform apply -auto-approve

register:arm64:
  extends: .runner
  stage: register
  script:
    - terraform apply -auto-approve

test:arm:
  extends: .image
  tags:
    - docker
    - arm
  script:
    - make build
  except:
    - master

test:arm64:
  extends: .image
  tags:
    - docker
    - arm64
  script:
    - make build-alpine
  except:
    - master

img:arm:
  extends: .image
  only:
    - master
  environment:
    name: arm/docker_images
    url: https://hub.docker.com/r/klud/gitlab-runner/tags/ 

img:arm64:
  extends: .image
  only:
    - master
  script:
    - make all-arm64
  environment:
    name: arm64/docker_images
    url: https://hub.docker.com/r/klud/gitlab-runner/tags/ 

unregister:arm:
  extends: .runner
  stage: unregister
  script:
    - terraform destroy -auto-approve
  dependencies:
    - register:arm
  needs:
    - register:arm
  when: always

unregister:arm64:
  extends: .runner
  stage: unregister
  script:
    - terraform destroy -auto-approve
  dependencies:
    - register:arm64
  needs:
    - register:arm64
  when: always