stages:
  - build
  - release

.binaries: &binaries
  image: klud/upx-base:armhf
  stage: build
  only:
    - upx-stable@klud/gitlab-runner
  tags:
    - docker
  script:
    - source ci/compress_binaries
    - make compress VERSION=$(VERSION)
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - binaries/gitlab-ci-multi-runner
      - binaries/docker-machine
    expire_in: 1 week

.image: &image
  image: klud/dind:17.03.1
  stage: release
  services: 
    - klud/dind:17.03.1
  variables:
    DOCKER_DRIVER: overlay
  only:
    - upx-stable@klud/gitlab-runner
  tags:
    - docker
  script:
    - source ci/relase_docker_images
    - make release

binaries: *binaries
runner:
  <<: *image
  dependencies:
    - binaries
  environment:
    name: stable/docker_images
    url: https://hub.docker.com/r/klud/gitlab-runner/tags/