stages:
  - upx-binaries
  - build_release

binaries:
  image: multiarch/alpine:armhf-v3.5
  stage: upx-binaries
  only:
    - upx@klud/gitlab-runner
  tags:
    - docker
  script:
    - apk add --no-cache bash wget
    - echo "http://dl-cdn.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories
    - echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
    - echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
    - wget -q https://gitlab-ci-multi-runner-downloads.s3.amazonaws.com/v9.2.1/binaries/gitlab-ci-multi-runner-linux-arm -O binaries/gitlab-ci-multi-runner
    - wget -q https://github.com/docker/machine/releases/download/v0.10.0/docker-machine-Linux-armhf -O binaries/docker-machine
    - apk add --no-cache upx
    - cd binaries
    - chmod +x gitlab-ci-multi-runner docker-machine
    - upx -9v gitlab-ci-multi-runner
    - upx -9v docker-machine
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - binaries/gitlab-ci-multi-runner
      - binaries/docker-machine
    expire_in: 1 week

runner:
  image: klud/docker:17.03.1
  services:
    - klud/dind:17.03.1
  stage: build_release
  dependencies:
    - binaries
  variables:
    DOCKER_DRIVER: overlay
    VER: '9.2.1-upx'
  only:
    - upx@klud/gitlab-runner
  tags:
    - docker
  script:
    # Login to registries
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    # Build the actual image
    - docker build --no-cache -t klud/gitlab-runner:$VER .
    # Tag the image for Docker Hub
    - docker tag klud/gitlab-runner:$VER klud/gitlab-runner:upx
    # Tag the image for GitLab Registry
    - docker tag klud/gitlab-runner:$VER registry.gitlab.com/klud/gitlab-runner:$VER
    - docker tag klud/gitlab-runner:$VER registry.gitlab.com/klud/gitlab-runner:upx
    # Push the image to Docker Hub
    - docker push klud/gitlab-runner:$VER
    - docker push klud/gitlab-runner:upx
    # Push the image to GitLab Registry
    - docker push registry.gitlab.com/klud/gitlab-runner:$VER
    - docker push registry.gitlab.com/klud/gitlab-runner:upx
    # Remove image from host after being pushed to the registry
    - docker rmi registry.gitlab.com/klud/gitlab-runner:upx
    - docker rmi registry.gitlab.com/klud/gitlab-runner:$VER
    - docker rmi klud/gitlab-runner:upx
    - docker rmi klud/gitlab-runner:$VER