build:
  image: klud/docker:1.13-armhf
  services:
    - klud/dind:1.13-armhf
  stage: build
  # When using dind, it's wise to use the overlayfs driver
  # for improved performance.
  variables:
    DOCKER_DRIVER: overlay
    VER: '0.1'
  tags:
    - armhf
  script:
    # Login to registries
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    # Build the actual image
    - docker build -t klud/gitlab-runner:$VER .
    # Tag the image for Docker Hub
    - docker tag klud/gitlab-runner:$VER klud/gitlab-runner:armhf
    - docker tag klud/gitlab-runner:$VER klud/gitlab-runner:latest
    # Tag the image for GitLab Registry
    - docker tag klud/gitlab-runner:$VER registry.gitlab.com/klud/gitlab-runner:$VER
    - docker tag klud/gitlab-runner:$VER registry.gitlab.com/klud/gitlab-runner:armhf
    - docker tag klud/gitlab-runner:$VER registry.gitlab.com/klud/gitlab-runner:latest
    # Push the image to Docker Hub
    - docker push klud/gitlab-runner:$VER
    - docker push klud/gitlab-runner:armhf
    - docker push klud/gitlab-runner:latest
    # Push the image to GitLab Registry
    - docker push registry.gitlab.com/klud/gitlab-runner:$VER
    - docker push registry.gitlab.com/klud/gitlab-runner:armhf
    - docker push registry.gitlab.com/klud/gitlab-runner:latest
    # Remove image from host after being pushed to the registry
    - docker rmi registry.gitlab.com/klud/gitlab-runner:latest
    - docker rmi registry.gitlab.com/klud/gitlab-runner:armhf
    - docker rmi registry.gitlab.com/klud/gitlab-runner:$VER
    - docker rmi klud/gitlab-runner:latest
    - docker rmi klud/gitlab-runner:armhf
    - docker rmi klud/gitlab-runner:$VER
