stages:
  - build
  - release

.binaries: &binaries
  image: klud/upx-base:armhf
  stage: build
  only:
    - upx-stable@klud/gitlab-runner
  tags:
    - build
  script:
    - export VER=$(echo $CI_JOB_NAME | sed 's|binaries ||')
    - mkdir -p binaries
    - wget -q https://gitlab-ci-multi-runner-downloads.s3.amazonaws.com/v${VER}/binaries/gitlab-ci-multi-runner-linux-arm -O binaries/gitlab-ci-multi-runner
    - wget -q https://github.com/docker/machine/releases/download/v0.10.0/docker-machine-Linux-armhf -O binaries/docker-machine
    - cd binaries
    - chmod +x gitlab-ci-multi-runner docker-machine
    - upx -9v gitlab-ci-multi-runner
    - upx -9v docker-machine
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - binaries/gitlab-ci-multi-runner
      - binaries/docker-machine
    expire_in: 1 week

.image: &image
  image: klud/dind:17.03.1
  stage: release
  services: 
    - klud/dind:17.03.1
  variables:
    DOCKER_DRIVER: overlay
  only:
    - master@klud/gitlab-runner
  tags:
    - docker
  script:
    - export VER=$(echo $CI_JOB_NAME | sed 's|runner ||')
    # Build the actual image
    - docker build --no-cache -t klud/gitlab-runner:$VER .
    # Tag the image for Docker Hub
    - docker tag klud/gitlab-runner:$VER klud/gitlab-runner:armhf
    - docker tag klud/gitlab-runner:$VER klud/gitlab-runner:latest
    # Tag the image for GitLab Registry
    - docker tag klud/gitlab-runner:$VER registry.gitlab.com/klud/gitlab-runner:$VER
    - docker tag klud/gitlab-runner:$VER registry.gitlab.com/klud/gitlab-runner:armhf
    - docker tag klud/gitlab-runner:$VER registry.gitlab.com/klud/gitlab-runner:latest
    # Login to registries
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    # Push the image to Docker Hub
    - docker push klud/gitlab-runner:$VER
    - docker push klud/gitlab-runner:armhf
    - docker push klud/gitlab-runner:latest
    # Push the image to GitLab Registry
    - docker push registry.gitlab.com/klud/gitlab-runner:$VER
    - docker push registry.gitlab.com/klud/gitlab-runner:armhf
    - docker push registry.gitlab.com/klud/gitlab-runner:latest
    # Logout of registries
    - docker logout
    - docker logout registry.gitlab.com
    # Remove image from host after being pushed to the registry
    - docker rmi registry.gitlab.com/klud/gitlab-runner:latest
    - docker rmi registry.gitlab.com/klud/gitlab-runner:armhf
    - docker rmi registry.gitlab.com/klud/gitlab-runner:$VER
    - docker rmi klud/gitlab-runner:latest
    - docker rmi klud/gitlab-runner:armhf
    - docker rmi klud/gitlab-runner:$VER

binaries 9.3.0: *binaries
runner 9.3.0:
  <<: *images
  dependencies:
    - binaries 9.3.0