stages:
  - build

.binaries: &binaries
  image: klud/upx-base:armhf
  stage: build
  only:
    - upx-stable@klud/gitlab-runner
  tags:
    - docker
  script:
    - source ci/compress_binaries
    - make compress
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - binaries/gitlab-ci-multi-runner
      - binaries/docker-machine
    expire_in: 1 week

binaries: *binaries