build:
  image: klud/docker:1.13-armhf
  services:
    - klud/dind:1.13-armhf
  stage: build
  # When using dind, it's wise to use the overlayfs driver for
  # improved performance.
  variables:
    DOCKER_DRIVER: overlay
  tags:
    - armhf
  script:
      - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
      - docker build -t registry.gitlab.com/klud/gitlab-runner:0.1 .
      - docker tag registry.gitlab.com/klud/gitlab-runner:0.1 registry.gitlab.com/klud/gitlab-runner:armhf
      - docker tag registry.gitlab.com/klud/gitlab-runner:0.1 registry.gitlab.com/klud/gitlab-runner:latest
      - docker push registry.gitlab.com/klud/gitlab-runner:0.1
      - docker push registry.gitlab.com/klud/gitlab-runner:armhf
      - docker push registry.gitlab.com/klud/gitlab-runner:latest
      # Delete image from host after being pushed to the registry
      - docker rmi registry.gitlab.com/klud/gitlab-runner:latest
      - docker rmi registry.gitlab.com/klud/gitlab-runner:armhf
      - docker rmi registry.gitlab.com/klud/gitlab-runner:0.1
