stages:
  # - build
  - release

# .binaries: &binaries
#   image: multiarch/alpine:armhf-v3.6
#   stage: build
#   only:
#     - master
#   tags:
#     - docker
#   script:
#     - source ci/upx_dependencies
#     - make compress
#   artifacts:
#     name: "$CI_JOB_NAME"
#     paths:
#       - binaries/gitlab-ci-multi-runner
#       - binaries/docker-machine
#     expire_in: 1 week

.image: &image
  image: klud/docker:17.03.1
  stage: release
  services: 
    - klud/dind:17.03.1
  variables:
    DOCKER_DRIVER: overlay
  only:
    - master
  tags:
    - docker
    - armhf
  script:
    - apk add --no-cache make bash
    - make release

# binaries: *binaries
runner:
  <<: *image
  dependencies:
    - binaries
  environment:
    name: stable/docker_images
    url: https://hub.docker.com/r/klud/gitlab-runner/tags/
    