stages:
  - images

.image: &image
  image: klud/docker:17.06.2
  stage: images
  services:
    - klud/docker:17.06.2-dind
  variables:
    DOCKER_DRIVER: overlay2
  only:
    - master
  tags:
    - docker
    - arm
  script:
    - apk add --no-cache make bash
    - make all

runner:
  <<: *image
  environment:
    name: stable/docker_images
    url: https://hub.docker.com/r/klud/gitlab-runner/tags/
    