stages:
  - build

.binaries: &binaries
  image: klud/upx-base:armhf
  stage: build
  only:
    - upx-stable@klud/gitlab-runner
  tags:
    - docker
  script:
    - export VER=$(echo $CI_JOB_NAME | sed 's|binaries ||')
    - mkdir -p binaries
    - wget -q https://gitlab-ci-multi-runner-downloads.s3.amazonaws.com/v${VER}/binaries/gitlab-ci-multi-runner-linux-arm -O binaries/gitlab-ci-multi-runner
    - wget -q https://github.com/docker/machine/releases/download/v0.10.0/docker-machine-Linux-armhf -O binaries/docker-machine
    - cd binaries
    - chmod +x gitlab-ci-multi-runner docker-machine
    - upx -9v gitlab-ci-multi-runner
    - upx -9v docker-machine
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - binaries/gitlab-ci-multi-runner
      - binaries/docker-machine
    expire_in: 1 week

binaries 9.3.0: *binaries