stages:
  - images

.image:
  image: docker:17.12
  stage: images
  services:
    - docker:17.12-dind
  variables:
    DOCKER_DRIVER: overlay2
  tags:
    - docker
    - arm
  before_script:
    - apk add --no-cache make bash
  script:
    - make all

test:
  extends: .image
  script:
    - make build
  except:
    - master

runner:
  extends: .image
  only:
    - master
  environment:
    name: stable/docker_images
    url: https://hub.docker.com/r/klud/gitlab-runner/tags/ 
